Repository arclix/core, pull requests merged in 2023-05, with the labels that each got.

#86 release: v0.1.3
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/index.ts
Labels: documentation, enhancement, release

#89 fix(generate): cwd bug in component generation (#88)
  src/create/GenerateConfigFile.ts
  src/generate/GenerateComponent.ts
  src/generate/helpers/getConfig.ts
  src/generate/helpers/getPackageFile.ts
  src/generate/helpers/getRootDirectory.ts
  src/generate/helpers/getRootPath.ts
  src/generate/helpers/index.ts
  src/tests/getRootDirectory.test.ts
  src/tests/getRootPath.test.ts
Labels: bug, mustfix, p1-bug

#92 feat(generate)!: add support to storybook in component generation (#85)
  src/create/GenerateConfigFile.ts
  src/generate/GenerateComponent.ts
  src/generate/GenerateComponentUtility.ts
  src/generate/helpers/checkProperty.ts
  src/generate/helpers/checkReact.ts
  src/generate/helpers/getConfig.ts
  src/generate/helpers/getPackageFile.ts
  src/generate/helpers/getRootDirectory.ts
  src/generate/templates/component.ts
  src/generate/templates/index.ts
  src/generate/templates/story.ts
  src/generate/templates/test.ts
  src/index.ts
  src/tests/componentTemplate.test.ts
  src/tests/storyTemplate.test.ts
  src/tests/testTemplate.test.ts
  src/types/type.ts
Labels: documentation, enhancement, p2-enhancement

#93 feat: update component and test templates to be generic (#90)
  src/generate/templates/component.ts
  src/generate/templates/test.ts
  src/tests/componentTemplate.test.ts
  src/tests/testTemplate.test.ts
Labels: documentation, enhancement, p2-enhancement

#94 ci: workflow to publish on npm registery (#71)
  .github/workflows/cd.yml
Labels: enhancement, p3-enhancement

#99 release: v0.1.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation, enhancement, release

#101 fix(ci): invalid build command
  .github/workflows/cd.yml
Labels: bug, p1-bug

#102 chore(changelog): update changelog for v0.1.4
  CHANGELOG.md
Labels: documentation, enhancement, release

#103 chore: fix indentaion in changelog
  CHANGELOG.md
Labels: bug, release

#105 chore: update lint rule and formatting
  .eslintrc.cjs
  .github/COMMIT_CONVENTION.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  commitlint.config.cjs
  commitlint.config.cts
  package-lock.json
  package.json
  src/create/CreateProject.ts
  src/create/GenerateConfigFile.ts
  src/generate/GenerateComponent.ts
  src/generate/GenerateComponentUtility.ts
  src/generate/GenerateConfigFile.ts
  src/generate/helpers/checkReact.ts
  src/generate/helpers/getConfig.ts
  src/generate/helpers/getPackageFile.ts
  src/generate/helpers/getRootDirectory.ts
  src/generate/helpers/index.ts
  src/generate/templates/component.ts
  src/generate/templates/index.ts
  src/generate/templates/story.ts
  src/generate/templates/test.ts
  src/index.ts
  src/mocks/arclix.config.json
  src/mocks/mock.package.json
  src/tests/checkReact.test.ts
  src/tests/componentTemplate.test.ts
  src/tests/generateComponent.test.ts
  src/tests/getConfig.test.ts
  src/tests/getPackageFile.test.ts
  src/tests/getRootDirectory.test.ts
  src/tests/storyTemplate.test.ts
  src/tests/testTemplate.test.ts
  src/types/decorator.ts
  src/types/type.ts
  src/utilities/utility.ts
  tsconfig.json
  vitest.config.ts
Labels: documentation, enhancement, p3-enhancement

#106 chore: update readme file with updated links
  README.md
Labels: documentation, enhancement, p3-enhancement

#107 feat(generate)!: add dynamic component type support in config (#95)
  src/generate/GenerateComponent.ts
  src/generate/GenerateComponentUtility.ts
  src/generate/GenerateConfigFile.ts
  src/generate/helpers/checkReact.ts
  src/index.ts
  src/tests/generateComponent.test.ts
  src/tests/getRootDirectory.test.ts
Labels: documentation, enhancement, p2-enhancement

#108 refactor(core)!: remove create module from arclix
  README.md
  package-lock.json
  package.json
  src/create/CreateProject.ts
  src/index.ts
  src/utilities/utility.ts
Labels: documentation, enhancement

#109 release: v0.1.5
  CHANGELOG.md
  package-lock.json
  package.json
  src/index.ts
Labels: documentation, enhancement, release

#111 chore(readme): update the links in readme to latest
  README.md
Labels: documentation, enhancement, accessibility
